// Liste centralisée des templates de service pour devis
export const SERVICE_TEMPLATES = {
  'Électricité générale': [
    { description: 'Tableau électrique', quantity: 1, unitPrice: 120 },
    { description: 'Disjoncteur divisionnaire', quantity: 8, unitPrice: 14 },
    { description: 'Prise électrique', quantity: 20, unitPrice: 7 },
    { description: 'Interrupteur', quantity: 10, unitPrice: 8 },
    { description: 'Câble 3G2.5mm²', quantity: 100, unitPrice: 1.2 },
    { description: 'Goulotte', quantity: 20, unitPrice: 3 },
    { description: 'Boîte d’encastrement', quantity: 15, unitPrice: 2 },
    { description: 'Spot LED encastrable', quantity: 8, unitPrice: 12 },
    { description: 'Appareillage complet', quantity: 1, unitPrice: 70 },
    { description: 'Main d’œuvre électricité', quantity: 16, unitPrice: 38 },
  ],
  'Plomberie sanitaire': [
    { description: 'Lavabo céramique', quantity: 2, unitPrice: 65 },
    { description: 'WC suspendu', quantity: 2, unitPrice: 210 },
    { description: 'Douche à l’italienne', quantity: 1, unitPrice: 420 },
    { description: 'Robinet mitigeur', quantity: 4, unitPrice: 48 },
    { description: 'Tube PER', quantity: 40, unitPrice: 1.5 },
    { description: 'Siphon', quantity: 4, unitPrice: 7 },
    { description: 'Chauffe-eau électrique', quantity: 1, unitPrice: 320 },
    { description: 'Raccord laiton', quantity: 10, unitPrice: 3 },
    { description: 'Main d’œuvre plomberie', quantity: 14, unitPrice: 36 },
  ],
  'Climatisation / Ventilation': [
    { description: 'Split mural', quantity: 2, unitPrice: 520 },
    { description: 'Pompe à chaleur air/air', quantity: 1, unitPrice: 1850 },
    { description: 'Grille de soufflage', quantity: 4, unitPrice: 16 },
    { description: 'Gaine isolée', quantity: 25, unitPrice: 9 },
    { description: 'Support mural', quantity: 2, unitPrice: 24 },
    { description: 'Thermostat connecté', quantity: 1, unitPrice: 95 },
    { description: 'Main d’œuvre climatisation', quantity: 10, unitPrice: 42 },
  ],
  'Domotique & Smart Home': [
    { description: 'Box domotique', quantity: 1, unitPrice: 180 },
    { description: 'Module volet roulant connecté', quantity: 6, unitPrice: 49 },
    { description: 'Détecteur de fumée connecté', quantity: 3, unitPrice: 39 },
    { description: 'Prise connectée', quantity: 8, unitPrice: 25 },
    { description: 'Caméra IP', quantity: 2, unitPrice: 65 },
    { description: 'Interrupteur sans fil', quantity: 6, unitPrice: 19 },
    { description: 'Main d’œuvre domotique', quantity: 8, unitPrice: 40 },
  ],
  'VRD (Voirie & Réseaux Divers)': [
    { description: 'Regard béton', quantity: 2, unitPrice: 49 },
    { description: 'Tuyau PVC assainissement', quantity: 40, unitPrice: 7 },
    { description: 'Gravier 20/40', quantity: 8, unitPrice: 45 },
    { description: 'Regards de visite', quantity: 2, unitPrice: 39 },
    { description: 'Bordure T2', quantity: 12, unitPrice: 13 },
    { description: 'Béton de propreté', quantity: 4, unitPrice: 120 },
    { description: 'Main d’œuvre VRD', quantity: 12, unitPrice: 37 },
  ],
  'Photovoltaïque': [
    { description: 'Panneau solaire 375W', quantity: 8, unitPrice: 210 },
    { description: 'Micro-onduleur', quantity: 8, unitPrice: 89 },
    { description: 'Structure de fixation', quantity: 8, unitPrice: 45 },
    { description: 'Coffret AC/DC', quantity: 1, unitPrice: 120 },
    { description: 'Câble solaire', quantity: 40, unitPrice: 2.5 },
    { description: 'Connecteur MC4', quantity: 16, unitPrice: 3 },
    { description: 'Main d’œuvre photovoltaïque', quantity: 18, unitPrice: 45 },
  ],
  'Piscine': [
    { description: 'Kit piscine coque', quantity: 1, unitPrice: 6500 },
    { description: 'Filtration à sable', quantity: 1, unitPrice: 420 },
    { description: 'Pompe piscine', quantity: 1, unitPrice: 340 },
    { description: 'Margelle pierre', quantity: 30, unitPrice: 19 },
    { description: 'Liner piscine', quantity: 35, unitPrice: 23 },
    { description: 'Projecteur LED', quantity: 2, unitPrice: 65 },
    { description: 'Main d’œuvre piscine', quantity: 30, unitPrice: 48 },
  ],
  'Carrelage extérieur': [
    { description: 'Carrelage grès cérame extérieur', quantity: 30, unitPrice: 35 },
    { description: 'Plinthe assortie', quantity: 18, unitPrice: 6 },
    { description: 'Colle carrelage extérieur', quantity: 8, unitPrice: 18 },
    { description: 'Joint carrelage extérieur', quantity: 4, unitPrice: 12 },
    { description: 'Ragréage extérieur', quantity: 5, unitPrice: 16 },
    { description: 'Primaire d’accrochage', quantity: 2, unitPrice: 22 },
    { description: 'Mortier de scellement', quantity: 3, unitPrice: 10 },
    { description: 'Croisillons', quantity: 2, unitPrice: 4 },
    { description: 'Profilé de finition', quantity: 10, unitPrice: 7 },
    { description: 'Seau de nettoyage', quantity: 1, unitPrice: 8 },
    { description: 'Éponge à joints', quantity: 2, unitPrice: 3 },
    { description: 'Genouillères', quantity: 1, unitPrice: 13 },
    { description: 'Main d’œuvre pose carrelage', quantity: 20, unitPrice: 40 },
    { description: 'Main d’œuvre préparation/support', quantity: 10, unitPrice: 38 },
    { description: 'Évacuation gravats', quantity: 2, unitPrice: 45 },
  ],
  'Menuiserie intérieure': [
    { description: 'Porte intérieure bois', quantity: 4, unitPrice: 90 },
    { description: 'Bloc-porte complet', quantity: 2, unitPrice: 160 },
    { description: 'Poignée de porte', quantity: 4, unitPrice: 18 },
    { description: 'Serrure', quantity: 2, unitPrice: 22 },
    { description: 'Plinthe bois', quantity: 22, unitPrice: 6 },
    { description: 'Parquet stratifié', quantity: 30, unitPrice: 28 },
    { description: 'Sous-couche parquet', quantity: 30, unitPrice: 3 },
    { description: 'Barre de seuil', quantity: 5, unitPrice: 9 },
    { description: 'Colle à bois', quantity: 2, unitPrice: 7 },
    { description: 'Visserie/chevilles', quantity: 2, unitPrice: 8 },
    { description: 'Silicone', quantity: 2, unitPrice: 5 },
    { description: 'Main d’œuvre pose parquet', quantity: 12, unitPrice: 35 },
    { description: 'Main d’œuvre pose porte', quantity: 6, unitPrice: 33 },
    { description: 'Dépose ancienne menuiserie', quantity: 2, unitPrice: 20 },
  ],
  'Menuiserie extérieure / Fenêtres': [
    { description: 'Fenêtre PVC double vitrage', quantity: 4, unitPrice: 210 },
    { description: 'Fenêtre aluminium', quantity: 2, unitPrice: 350 },
    { description: 'Volet roulant manuel', quantity: 3, unitPrice: 140 },
    { description: 'Volet roulant motorisé', quantity: 1, unitPrice: 260 },
    { description: 'Seuil aluminium', quantity: 4, unitPrice: 19 },
    { description: 'Joint d’étanchéité', quantity: 10, unitPrice: 2 },
    { description: 'Vitrage sécurité', quantity: 2, unitPrice: 65 },
    { description: 'Bavette aluminium', quantity: 5, unitPrice: 7 },
    { description: 'Mousse expansive', quantity: 2, unitPrice: 6 },
    { description: 'Silicone extérieur', quantity: 2, unitPrice: 6 },
    { description: 'Visserie spéciale', quantity: 2, unitPrice: 10 },
    { description: 'Main d’œuvre pose fenêtre', quantity: 10, unitPrice: 38 },
    { description: 'Dépose ancienne fenêtre', quantity: 2, unitPrice: 25 },
    { description: 'Évacuation déchets', quantity: 1, unitPrice: 40 },
  ],
  'Isolation thermique': [
    { description: 'Laine de verre', quantity: 60, unitPrice: 7 },
    { description: 'Laine de roche', quantity: 40, unitPrice: 8 },
    { description: 'Panneau polyuréthane', quantity: 30, unitPrice: 13 },
    { description: 'Pare-vapeur', quantity: 50, unitPrice: 1.5 },
    { description: 'Suspente', quantity: 80, unitPrice: 0.7 },
    { description: 'Fourrure métallique', quantity: 60, unitPrice: 2.5 },
    { description: 'Bande adhésive', quantity: 3, unitPrice: 5 },
    { description: 'Rosace d’isolation', quantity: 60, unitPrice: 0.3 },
    { description: 'Cheville à frapper', quantity: 2, unitPrice: 12 },
    { description: 'Mousse PU', quantity: 2, unitPrice: 6 },
    { description: 'Main d’œuvre pose isolation', quantity: 16, unitPrice: 36 },
    { description: 'Location échafaudage', quantity: 2, unitPrice: 35 },
    { description: 'Évacuation déchets', quantity: 2, unitPrice: 40 },
  ],
  'Terrasse bois': [
    { description: 'Lame bois exotique', quantity: 20, unitPrice: 42 },
    { description: 'Lame composite', quantity: 10, unitPrice: 49 },
    { description: 'Lambourde bois', quantity: 40, unitPrice: 7 },
    { description: 'Plot réglable', quantity: 30, unitPrice: 3 },
    { description: 'Bande bitumeuse', quantity: 2, unitPrice: 15 },
    { description: 'Vis inox terrasse', quantity: 2, unitPrice: 14 },
    { description: 'Géotextile', quantity: 20, unitPrice: 1.5 },
    { description: 'Huile de protection', quantity: 2, unitPrice: 24 },
    { description: 'Scie sauteuse', quantity: 1, unitPrice: 18 },
    { description: 'Main d’œuvre pose terrasse', quantity: 14, unitPrice: 39 },
    { description: 'Dépose ancienne terrasse', quantity: 10, unitPrice: 15 },
    { description: 'Évacuation gravats', quantity: 2, unitPrice: 38 },
  ],
  'Maçonnerie paysagère': [
    { description: 'Pavé béton', quantity: 40, unitPrice: 19 },
    { description: 'Pavé granit', quantity: 20, unitPrice: 44 },
    { description: 'Bordure béton', quantity: 20, unitPrice: 11 },
    { description: 'Sable stabilisé', quantity: 5, unitPrice: 38 },
    { description: 'Géotextile', quantity: 10, unitPrice: 1.3 },
    { description: 'Joint polymère', quantity: 2, unitPrice: 32 },
    { description: 'Béton prêt à l’emploi', quantity: 2, unitPrice: 120 },
    { description: 'Location plaque vibrante', quantity: 1, unitPrice: 25 },
    { description: 'Main d’œuvre pose pavé', quantity: 12, unitPrice: 36 },
    { description: 'Évacuation terre/gravat', quantity: 2, unitPrice: 39 },
  ],
  'Chauffage / Plomberie chauffage': [
    { description: 'Radiateur acier', quantity: 4, unitPrice: 110 },
    { description: 'Radiateur fonte', quantity: 2, unitPrice: 260 },
    { description: 'Chaudière gaz condensation', quantity: 1, unitPrice: 2100 },
    { description: 'Chaudière électrique', quantity: 1, unitPrice: 1400 },
    { description: 'Thermostat programmable', quantity: 1, unitPrice: 120 },
    { description: 'Tube multicouche', quantity: 30, unitPrice: 2.5 },
    { description: 'Raccord laiton', quantity: 10, unitPrice: 3 },
    { description: 'Purgeur automatique', quantity: 2, unitPrice: 18 },
    { description: 'Circulateur', quantity: 1, unitPrice: 140 },
    { description: 'Vanne d’arrêt', quantity: 4, unitPrice: 11 },
    { description: 'Main d’œuvre installation', quantity: 20, unitPrice: 42 },
    { description: 'Mise en service', quantity: 1, unitPrice: 180 },
  ],
  'Peinture façade': [
    { description: 'Peinture acrylique façade', quantity: 8, unitPrice: 85 },
    { description: 'Peinture siloxane', quantity: 4, unitPrice: 110 },
    { description: 'Sous-couche façade', quantity: 4, unitPrice: 65 },
    { description: 'Filet de protection', quantity: 20, unitPrice: 1.5 },
    { description: 'Échafaudage', quantity: 2, unitPrice: 35 },
    { description: 'Ruban adhésif extérieur', quantity: 2, unitPrice: 5 },
    { description: 'Enduit de rebouchage', quantity: 3, unitPrice: 19 },
    { description: 'Brosse façade', quantity: 2, unitPrice: 7 },
    { description: 'Rouleau façade', quantity: 2, unitPrice: 9 },
    { description: 'Nettoyeur haute pression', quantity: 1, unitPrice: 28 },
    { description: 'Main d’œuvre peinture', quantity: 12, unitPrice: 34 },
    { description: 'Protection sol', quantity: 30, unitPrice: 1.2 },
  ],
  'Maison': [
    { description: 'Parpaing', quantity: 10, unitPrice: 90 },
    { description: 'Ciment', quantity: 30, unitPrice: 8 },
    { description: 'Sable', quantity: 2, unitPrice: 45 },
    { description: 'Fer à béton', quantity: 0.3, unitPrice: 850 },
    { description: 'Treillis soudé', quantity: 15, unitPrice: 7 },
    { description: 'Gravier', quantity: 1, unitPrice: 35 },
    { description: 'Béton prêt à l’emploi', quantity: 3, unitPrice: 120 },
    { description: 'Linteau béton', quantity: 4, unitPrice: 35 },
    { description: 'Hourdis', quantity: 20, unitPrice: 5 },
    { description: 'Main d’œuvre', quantity: 10, unitPrice: 35 },
  ],
  'Toiture': [
    { description: 'Tuiles', quantity: 35, unitPrice: 28 },
    { description: 'Liteaux', quantity: 40, unitPrice: 1 },
    { description: 'Écran sous-toiture', quantity: 35, unitPrice: 3 },
    { description: 'Chevrons', quantity: 20, unitPrice: 4 },
    { description: 'Clous/vis toiture', quantity: 2, unitPrice: 7 },
    { description: 'Isolation toiture', quantity: 35, unitPrice: 8 },
    { description: 'Gouttière PVC', quantity: 15, unitPrice: 6 },
    { description: 'Main d’œuvre', quantity: 12, unitPrice: 38 },
  ],
  'Salle de bain': [
    { description: 'Carrelage sol', quantity: 8, unitPrice: 23 },
    { description: 'Carrelage mural', quantity: 12, unitPrice: 18 },
    { description: 'Receveur de douche', quantity: 1, unitPrice: 180 },
    { description: 'Paroi de douche', quantity: 1, unitPrice: 220 },
    { description: 'Robinetterie', quantity: 1, unitPrice: 90 },
    { description: 'WC suspendu', quantity: 1, unitPrice: 280 },
    { description: 'Meuble vasque', quantity: 1, unitPrice: 250 },
    { description: 'Peinture spéciale salle de bain', quantity: 2, unitPrice: 35 },
    { description: 'Joint silicone', quantity: 2, unitPrice: 7 },
    { description: 'Main d’œuvre', quantity: 10, unitPrice: 40 },
  ],
  'Électricité': [
    { description: 'Câble électrique', quantity: 80, unitPrice: 1 },
    { description: 'Tableau électrique', quantity: 1, unitPrice: 120 },
    { description: 'Disjoncteur', quantity: 10, unitPrice: 9 },
    { description: 'Prise électrique', quantity: 12, unitPrice: 5 },
    { description: 'Interrupteur', quantity: 8, unitPrice: 4 },
    { description: 'Goulotte', quantity: 12, unitPrice: 2 },
    { description: 'Boîte de dérivation', quantity: 5, unitPrice: 3 },
    { description: 'Gaine ICTA', quantity: 30, unitPrice: 1 },
    { description: 'Ampoule LED', quantity: 15, unitPrice: 3 },
    { description: 'Main d’œuvre', quantity: 15, unitPrice: 42 },
  ],
  'Peinture': [
    { description: 'Peinture blanche', quantity: 10, unitPrice: 29 },
    { description: 'Peinture couleur', quantity: 6, unitPrice: 34 },
    { description: 'Sous-couche', quantity: 8, unitPrice: 22 },
    { description: 'Enduit de lissage', quantity: 12, unitPrice: 16 },
    { description: 'Ruban de masquage', quantity: 3, unitPrice: 4 },
    { description: 'Bâche de protection', quantity: 30, unitPrice: 1 },
    { description: 'Brosse/pinceau', quantity: 4, unitPrice: 5 },
    { description: 'Rouleau peinture', quantity: 3, unitPrice: 7 },
    { description: 'Main d’œuvre', quantity: 8, unitPrice: 33 },
  ],
  'Plomberie': [
    { description: 'Tube cuivre', quantity: 10, unitPrice: 4 },
    { description: 'Tube PER', quantity: 10, unitPrice: 2 },
    { description: 'Robinet d’arrêt', quantity: 2, unitPrice: 8 },
    { description: 'Évier inox', quantity: 1, unitPrice: 95 },
    { description: 'Mitigeur évier', quantity: 1, unitPrice: 55 },
    { description: 'Siphon évier', quantity: 1, unitPrice: 12 },
    { description: 'Flexible alimentation', quantity: 2, unitPrice: 7 },
    { description: 'Joint plomberie', quantity: 1, unitPrice: 4 },
    { description: 'Main d’œuvre', quantity: 8, unitPrice: 39 },
  ],
};
