// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvnbfilbxqlkjfyzhvxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bmJmaWxieHFsa2pmeXpodnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NDk2ODcsImV4cCI6MjA5MDEyNTY4N30.haRld8pywh8E1xlLyqG1tXx6UfQ2g8HtL9Jvg2jOfuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);