// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emjrmsjmeihalxppqgec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtanJtc2ptZWloYWx4cHBxZ2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDQ1ODcsImV4cCI6MjA2NTA4MDU4N30.-_9qNfTK4R-dkNTu82FX_2VJFgAAtnTt7L2KdGO0gUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);